version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html     # Volumen persistente para los archivos de WordPress
      - ./uploads:/var/www/html/wp-content/uploads # Volumen persistente para los archivos subidos

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql         # Volumen persistente para los datos de la base de datos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somerootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass

volumes:
  db_data:
